name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Install Angular
      run: npm install -g @angular/cli@17

    - name: Install dependencies
      run: npm install

    - name: Build
      run: ng build --base-href=/github-d-mission/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/github-d-mission/browser
