name: Lint CI

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Use Node.js
      uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install -g @angular/cli@17

    - name: Linting
      run: ng lint
